version: '3.5'
services:
    db:
        hostname: "${WARDEN_ENV_NAME}-mariadb"
        image: mariadb:${MARIADB_VERSION:-10.3}
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
            - ./conf/mysql.cnf:/etc/mysql/my.cnf
        command:
            - mysqld
            - --max_allowed_packet=1024M
            - --explicit_defaults_for_timestamp=on
volumes:
    dbdata:
