version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER}
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - MAGENTO_MODE=${MAGENTO_MODE}
    privileged: true
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.template:/etc/nginx/conf.d/default.template
    command:
      /bin/bash -c "envsubst '$$TRAEFIK_DOMAIN$$MAGENTO_MODE' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
